---
-
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python2.7 
  tasks:
    - name: Install docker on centos7
      yum:
        name: java-1.8.0-openjdk.x86_64
        state: present

    - name: Install docker on centos7
      yum:
        name: docker
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
      
    - name: Run Shell Scripts for tomcat
      shell:
         "./install.sh"
      args:
         executable: /bin/bash

    - name: Run Shell Scripts for adding users
      shell:
         "./useradd.sh"
      args:
         executable: /bin/bash

    - name: Pulling Jenkins image
      docker_image:
        name: jenkins/jenkins
        state: present

    - name: Start container with healthstatus
      docker_container:
        name: jenkins-container
        image: jenkins/jenkins
        state: started
        ports:
          - "8080:8085"
        volumes: 
          - myjenkins
