---
-
  hosts: localhost
  become: yes
  become_method: sudo
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tasks:
    - name: Install docker on centos7
      yum:
        name: java-1.8.0-openjdk.x86_64

    - name: Install docker on centos7
      yum:
        name: docker
      
    - name: Run Shell Scripts for tomcat
      shell:
        cmd: sudo ./install.sh

    - name: Run Shell Scripts for adding users
      shell:
        cmd: sudo ./useradd.sh

    - name: Start container with healthstatus
      docker_container:
        name: jenkins-container
        image: jenkins/jenkins
        state: started
        ports:
          - "8080:8085"
        volumes: 
          - myjenkins
